version: '3.9'
services:
  node:
    build: .
    ports:
      - "9999:9999"
    links:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sebastiancb
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
