version: '3.9'
services:

  node:
    build: .
    ports:
      - "9999:9999"
    expose:
      - 9999
    links:
      - "mongoDB"
    networks:
      - default
  mongoDB:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sebastiancb
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    networks:
      - default
networks: 
  default:
    driver: bridge
volumes:
  mongo-data:
  
